config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'

  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :trips, except: :index do
    resources :locations, only: [ :create ]
  end
  resources :locations, only: [ :show, :edit, :update, :destroy ]

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	belongs_to :user
	has_many :locations, dependent: :destroy

  # Sort so that newest trips are shown first
	default_scope -> { order(created_at: :desc) }

	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 60 }
	validates :start_loc, presence: true
	validates :end_loc, presence: true

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

	before_action :logged_in_user
	before_action :correct_user, only: [:edit, :update, :destroy]

	def show
		@trip = Trip.find(params[:id])
		@locations = @trip.locations

		# Use to build location markers for map
		@hash = Gmaps4rails.build_markers(@locations) do |location, marker|
			marker.lat location.latitude
			marker.lng location.longitude
			# marker.infoWindow location.name
		end

		# Use for '+ Location' form in modal
		@location = Location.new
	end

	def new
		@trip = Trip.new
	end

	def create
		# Build automatically associates @trip with current_user
		@trip = current_user.trips.build(trip_params)
		if @trip.save
			flash[:success] = "Trip \'#{@trip.name}\' created!"
			redirect_to user_path(current_user)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @trip.update_attributes(trip_params)
			# Handle a successful update.
			flash[:success] = "Trip \'#{@trip.name}\' updated"
			redirect_to current_user
		else
			render 'edit'
		end
	end

	def destroy
		@trip.destroy
		flash[:success] = "Trip \'#{@trip.name}\' deleted"
		redirect_to request.referrer || root_url
	end


	private

		# Use strong parameters
		def trip_params
			params.require(:trip).permit(:name, :description, :start_loc, :end_loc)
		end

		def correct_user
			@trip = current_user.trips.find_by(id: params[:id])
			redirect_to root_url if @trip.nil?
		end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_trip.html.erb
<li id="trip-<%= trip.id %>">
	<h4 class="trip-name"><span class="glyphicon glyphicon-road"></span><%= link_to trip.name, trip_path(trip) %></h4>
	<span class="start-end-loc"><%= trip.start_loc %> -> <%= trip.end_loc %></span>
	<span class="description"><%= trip.description %></span>
	<small class="timestamp">
		Created <%= time_ago_in_words(trip.created_at) %> ago
		<% if current_user?(trip.user) %>
			| <%= link_to "edit", edit_trip_path(trip) %> |
		  <%= link_to "delete", trip, method: :delete, data: { confirm: "You sure?" } %>
		<% end %>
	</small>
</li>

app/views/trips/_trip_sidebar.html.erb
<aside class="col-md-3 trip_sidebar">
	<div class="trip_info">
		<%= link_to root_url, class: "btn-sm inline pull-left" do %>
			<span class="glyphicon glyphicon-arrow-left"></span>
			<span class="glyphicon glyphicon-th-list"></span>
		<% end %>
		<h3><%= @trip.name %></h3>
	</div>
	<hr>
	<div class="add_location center"
		<% if @trip.user == current_user %>
			<!-- Button trigger modal -->
				<button type="button" class="btn" data-toggle="modal" data-target="#newLocModal">
				  <span class="glyphicon glyphicon-plus"></span> Location
				</button>
				<%= render 'shared/new_loc_modal' %>
			<hr>
		<% end %>
	</div>
	<div class="loc-list">
		<% if @trip.locations.any? %>
			<ol class="locations">
					<%= render @trip.locations %>
			</ol>
		<% end %>
	</div>
</aside>

app/views/trips/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update trip information</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@trip) do |f| %>
			<%= render 'shared/error_messages', object: f.object %> <!-- render partial -->

			<%= f.label :trip_name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_field :description, class: 'form-control' %>

			<%= f.label :start_location %>
			<%= f.text_field :start_loc, class: 'form-control' %>

			<%= f.label :end_location %>
			<%= f.text_field :end_loc, class: 'form-control' %>

			<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/trips/new.html.erb
<% provide(:title, 'New trip') %>
<h1>Create new trip</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@trip) do |f| %>
			<%= render 'shared/error_messages', object: f.object %> <!-- render partial -->

			<%= f.label :trip_name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_field :description, class: 'form-control' %>

			<%= f.label :start_location %>
			<%= f.text_field :start_loc, class: 'form-control' %>

			<%= f.label :end_location %>
			<%= f.text_field :end_loc, class: 'form-control' %>

			<%= f.submit "Create trip", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/trips/show.html.erb
<% provide(:title, @trip.name) %>
<div class="row">
	<%= render 'trip_sidebar' %>
	<div class="col-md-9 center">
		<!-- Trip map -->
		<div>
		  <div id="trip_map" style='width: 850px; height: 600px;'></div>
		</div>
		<script type="text/javascript">
			handler = Gmaps.build('Google');
			handler.buildMap(
				{
					provider: {
						zoomControl: true,
						mapTypeControl: false,
						scaleControl: true,
						streetViewControl: false,
						rotateControl: false,

						zoom: 2
					},
					internal: {
						id: 'trip_map'
					}
				}, 
				function() {
					markers = handler.addMarkers(<%= raw @hash.to_json %>); 
					handler.bounds.extendWith(markers);
					handler.fitMapToBounds();
				});
		</script>
	</div>
</div>