config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'

  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :trips, except: :index do
    resources :locations, only: [ :create ]
  end
  resources :locations, only: [ :show, :edit, :update, :destroy ]

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :trip
	has_many :activities, dependent: :destroy

	geocoded_by :name
	# Avoid unnecessary API requests: only geocode object if loc name is present,
		#   has been changed since last save, or has never been saved
	after_validation :geocode, if: ->(obj){ obj.name.present? and obj.name_changed? }
	after_validation :lat_changed?

	validates :trip_id, presence: true
	validates :name, presence: true, length: { maximum: 60 }
	validates :arrival, presence: true
	validates :departure, presence: true

	private

		# Use to validate whether geocode was successful (location was valid)
		def lat_changed?
			if (self.name_changed? && !(self.latitude_changed?))
				# If name has changed but latitude didn't, geocoder didn't get returned lat/lng
				self.errors.add(:name, "\'#{self.name}\' is not a valid location")
				return false
			end
			return true
		end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

	def new
		@location = Location.new
	end

	def create
		@trip = Trip.find(params[:trip_id])
		@location = @trip.locations.build(loc_params)
		if @location.save
			flash[:success] = "\'#{@location.name}\' was added to \'#{@trip.name}\'!"
			redirect_to trip_path(@trip)
		else
			# Handle errors in location (ex. location not found, or form field blank)
			render 'new' # TEMPORARY FIX (should redisplay modal w/ error messages)
		end
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		if @location.update_attributes(loc_params)
			# Handle a successful update.
			flash[:success] = "Location \'#{@location.name}\' updated"
			redirect_to trip_path(@location.trip)
		else
			render 'edit'
		end
	end

	def destroy
		@location = Location.find(params[:id])
		@trip = @location.trip
		@location.destroy
		flash[:success] = "\'#{@location.name}\' has been removed from your trip"
		redirect_to trip_path(@trip)
	end

	private

		# Use strong parameters
		def loc_params
			params.require(:location).permit(:name, :arrival, :departure)
		end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_location.html.erb
<li id="location-<%= location.id %>">
	<h4 class="location-name"><%= location.name %></h4>
	<% if current_user?(location.trip.user) %>
		<div class="arrival"><span class="glyphicon glyphicon-log-in" aria-label="Arrival"></span><%= location.arrival.strftime("%a, %b %-d, %Y @ %l:%M%p") %></div>
		<div class="departure"><span class="glyphicon glyphicon-log-out" aria-label="Departure"></span><%= location.departure.strftime("%a, %b %-d, %Y @ %l:%M%p") %></div>
		<small>
			<%= link_to "edit", edit_location_path(location) %> |
	  	<%= link_to "delete", location, method: :delete, data: { confirm: "You sure?" } %>
		</small>
	<% end %>
</li>

app/views/locations/edit.html.erb
<% provide(:title, 'Edit Location Details') %>
<h1>Edit location details</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@location) do |f| %>
			<%= render 'shared/error_messages', object: f.object %> <!-- render partial -->

			<p class="center">Update arrival/departure for <%= @location.name %>:</p>

			<%= f.label :date_of_arrival %>
			<div><!-- extra divs are for bootstrap3-datetimepicker -->
		    <div>
	        <div>
	            <%= f.text_field :arrival, class: 'form-control datetimepicker', id: 'arrival-dtpicker', data: { date_format: 'YYYY-MM-DD HH:mm A' } %>
	        </div>
	        <script type="text/javascript">
	            $(function () {
	                $('#arrival-dtpicker').datetimepicker();
	            });
	        </script>
	    	</div>
			</div>

			<%= f.label :date_of_departure %>
			<div><!-- extra divs are for bootstrap3-datetimepicker -->
		    <div>
	        <div>
	            <%= f.text_field :departure, class: 'form-control datetimepicker', id: 'departure-dtpicker', data: { date_format: 'YYYY-MM-DD HH:mm A' } %>
	        </div>
	        <script type="text/javascript">
	            $(function () {
	                $('#departure-dtpicker').datetimepicker();
	            });
	        </script>
	    	</div>
			</div>

			<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/locations/new.html.erb
<% provide(:title, 'Add Location') %>
<h1>Add location</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for([@trip, @location]) do |f| %>
			<%= render 'shared/error_messages', object: f.object %> <!-- render partial -->

			<%= f.label :location %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :date_of_arrival %>
			<div><!-- extra divs are for bootstrap3-datetimepicker -->
		    <div>
	        <div>
	            <%= f.text_field :arrival, class: 'form-control datetimepicker', id: 'arrival-dtpicker', data: { date_format: 'YYYY-MM-DD HH:mm A' } %>
	        </div>
	        <script type="text/javascript">
	            $(function () {
	                $('#arrival-dtpicker').datetimepicker();
	            });
	        </script>
	    	</div>
			</div>

			<%= f.label :date_of_departure %>
			<div><!-- extra divs are for bootstrap3-datetimepicker -->
		    <div>
	        <div>
	            <%= f.text_field :departure, class: 'form-control datetimepicker', id: 'departure-dtpicker', data: { date_format: 'YYYY-MM-DD HH:mm A' } %>
	        </div>
	        <script type="text/javascript">
	            $(function () {
	                $('#departure-dtpicker').datetimepicker();
	            });
	        </script>
	    	</div>
			</div>

			<%= f.submit "Add location", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>